version: '3.7'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.monitoring.enabled: "true"
    volumes:
      - elkdata:/usr/share/elasticsearch/data
    networks:
      - elastic
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.0
    ports:
      - "9600:9600/udp"
        #command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      #- ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf:ro
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - elastic
      
volumes:
  elkdata: {}

networks:
  elastic:
